## R_p

 = sum[(배당금/환산종가) + ((현시점환산종가 - 이전시점환산종가)/이전시점환산종가)] / 시점수 * 각 기업 가중치

= sum(avg_returns * 각 기업 가중치)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
avg_returns = pd.read_excel('avg_returns.xlsx')

avg_returns

,Date,AFL,ALB,AOS,APD,ATO,BF-B,BRO,CHRW,CINF,...,PPG,ROP,SPGI,SWK,SYY,TGT,TROW,WMT,WST,XOM
0,2019-12-31,-0.019968,-0.007488,-0.022956,0.009149,0.005446,0.008785,0.025623,-0.018241,0.005449,...,-0.014560,-0.005501,0.013868,-0.015674,-0.015773,0.025601,0.006183,0.015776,0.022440,-0.045473
1,2020-12-31,0.044296,0.082188,0.055933,0.033451,0.005428,0.027846,0.022593,0.043741,0.038990,...,0.052720,0.027707,0.040157,0.062473,0.052984,0.059800,0.054021,0.020402,0.061850,0.053422
2,2021-12-31,0.022359,0.031126,0.008739,-0.007506,0.024360,-0.001991,0.035725,0.015048,0.022752,...,-0.007816,0.016198,0.017211,-0.017536,0.006179,0.020400,-0.006990,0.011277,0.036830,0.040337
3,2022-12-31,0.011208,0.024634,0.010341,0.025638,0.004048,0.002943,-0.011184,0.004699,-0.004661,...,0.008215,0.000330,-0.007385,-0.042290,-0.001176,-0.014542,-0.011416,0.003918,-0.003997,0.031337
4,2023-12-31,0.017081,-0.052927,0.015539,-0.017947,-0.001856,-0.017420,0.029647,-0.026068,0.001166,...,0.000726,0.013688,0.012326,0.008846,0.001121,0.000714,0.002273,0.015254,0.004341,-0.001844

In [3]:
df = avg_returns.copy()

df['Date'] = pd.to_datetime(df['Date'])

df['Date'] = df['Date'].dt.year

df

,Date,AFL,ALB,AOS,APD,ATO,BF-B,BRO,CHRW,CINF,...,PPG,ROP,SPGI,SWK,SYY,TGT,TROW,WMT,WST,XOM
0,2019,-0.019968,-0.007488,-0.022956,0.009149,0.005446,0.008785,0.025623,-0.018241,0.005449,...,-0.014560,-0.005501,0.013868,-0.015674,-0.015773,0.025601,0.006183,0.015776,0.022440,-0.045473
1,2020,0.044296,0.082188,0.055933,0.033451,0.005428,0.027846,0.022593,0.043741,0.038990,...,0.052720,0.027707,0.040157,0.062473,0.052984,0.059800,0.054021,0.020402,0.061850,0.053422
2,2021,0.022359,0.031126,0.008739,-0.007506,0.024360,-0.001991,0.035725,0.015048,0.022752,...,-0.007816,0.016198,0.017211,-0.017536,0.006179,0.020400,-0.006990,0.011277,0.036830,0.040337
3,2022,0.011208,0.024634,0.010341,0.025638,0.004048,0.002943,-0.011184,0.004699,-0.004661,...,0.008215,0.000330,-0.007385,-0.042290,-0.001176,-0.014542,-0.011416,0.003918,-0.003997,0.031337
4,2023,0.017081,-0.052927,0.015539,-0.017947,-0.001856,-0.017420,0.029647,-0.026068,0.001166,...,0.000726,0.013688,0.012326,0.008846,0.001121,0.000714,0.002273,0.015254,0.004341,-0.001844

In [9]:

def calculate_Rp(df, seed=42):
    np.random.seed(seed)
    tickers = df.columns[1:]  # 'Date'열 제외
    # num_tickers = len(tickers)
    num_tickers = 2

    selected_tickers = np.random.choice(tickers, num_tickers, replace=False)
    weights = np.random.random(num_tickers)
    weights /= weights.sum()  # 가중치 합 = 1로 조정
    
    annual_returns = df[selected_tickers]
    weighted_returns = annual_returns.multiply(weights, axis=1)
    Rp = weighted_returns.sum(axis=1)
    
    return Rp

Rp = calculate_Rp(df)

for year, rp in zip(df['Date'], Rp):
    print(f"Year: {year}, R_p: {rp:.6f}")

Year: 2019, R_p: 0.004013
Year: 2020, R_p: 0.040937
Year: 2021, R_p: 0.002979
Year: 2022, R_p: 0.019040
Year: 2023, R_p: 0.004622

In [8]:

def calculate_Rp(df, seed=42):
    np.random.seed(seed)
    tickers = df.columns[1:]  # 'Date'열 제외
    # num_tickers = len(tickers)
    num_tickers = 5

    selected_tickers = np.random.choice(tickers, num_tickers, replace=False)
    weights = np.random.random(num_tickers)
    weights /= weights.sum()  # 가중치 합 = 1로 조정
    
    annual_returns = df[selected_tickers]
    weighted_returns = annual_returns.multiply(weights, axis=1)
    Rp = weighted_returns.sum(axis=1)
    
    return Rp

Rp = calculate_Rp(df)

for year, rp in zip(df['Date'], Rp):
    print(f"Year: {year}, R_p: {rp:.6f}")

Year: 2019, R_p: -0.014509
Year: 2020, R_p: 0.038411
Year: 2021, R_p: 0.029059
Year: 2022, R_p: 0.007432
Year: 2023, R_p: 0.002898

In [7]:

def calculate_Rp(df, seed=42):
    np.random.seed(seed)
    tickers = df.columns[1:]  # 'Date'열 제외
    # num_tickers = len(tickers)
    num_tickers = 5

    selected_tickers = np.random.choice(tickers, num_tickers, replace=False)
    weights = np.random.random(num_tickers)
    weights /= weights.sum()  # 가중치 합 = 1로 조정
    
    annual_returns = df[selected_tickers]
    weighted_returns = annual_returns.multiply(weights, axis=1)
    Rp = weighted_returns.sum(axis=1)
    
    return Rp

Rp = calculate_Rp(df)

for year, rp in zip(df['Date'], Rp):
    print(f"Year: {year}, R_p: {rp:.6f}")

Year: 2019, R_p: -0.003507
Year: 2020, R_p: 0.042783
Year: 2021, R_p: 0.012714
Year: 2022, R_p: 0.001326
Year: 2023, R_p: 0.001258

In [5]:
# np.random.seed(42)

# # 'Date' 열을 제외한 기업 수
# num_companies = df.shape[1] - 1

# # 랜덤 가중치 생성
# weights = np.random.rand(num_companies)

# # 가중치의 합을 1로 두고 전규화
# weights /= weights.sum()

# # 각 연도별 R_p 계산 (이때 'Date' 열은 제외)
# returns = df.iloc[:, 1:].values
# portfolio_returns = returns @ weights

# result_df = pd.DataFrame({
#     'Date': df['Date'],
#     'R_p': portfolio_returns
# })

# # 결과 데이터프레임 표시
# result_df